### ISSUE TITLE
Table 'WSO2IS_IDENTITY_DB.CM_PURPOSE' doesn't exist

### ISSUE THREAD

**Issue by oscarvesga** [wso2/docker-is#198]
**Description:**
Hi, I get this error in the docker image wso2/wso2is:5.10.0 when I try to activated and tested the selft register proceed.

```identity-server_1  | [2020-04-07 02:50:12,673] [125d4bd4-ad4f-4b99-925f-c18181e66686] ERROR {org.wso2.carbon.consent.mgt.endpoint.impl.ConsentsApiServiceImpl} - Error occurred while listing purpose from DB for group: SELF-SIGNUP, groupType: SYSTEM limit: 100 and offset: 0. org.wso2.carbon.consent.mgt.core.exception.ConsentManagementServerException: Error occurred while listing purpose from DB for group: SELF-SIGNUP, groupType: SYSTEM limit: 100 and offset: 0.
identity-server_1  |    at org.wso2.carbon.consent.mgt.core.dao.impl.PurposeDAOImpl.listPurposes(PurposeDAOImpl.java:249)
identity-server_1  |    at org.wso2.carbon.consent.mgt.core.ConsentManagerImpl.listPurposes(ConsentManagerImpl.java:262)
identity-server_1  |    at org.wso2.carbon.consent.mgt.core.PrivilegedConsentManagerImpl$5.execute(PrivilegedConsentManagerImpl.java:226)
identity-server_1  |    at org.wso2.carbon.consent.mgt.core.PrivilegedConsentManagerImpl$5.execute(PrivilegedConsentManagerImpl.java:222)
identity-server_1  |    at org.wso2.carbon.consent.mgt.core.model.ConsentInterceptorTemplate.executeWith(ConsentInterceptorTemplate.java:56)
identity-server_1  |    at org.wso2.carbon.consent.mgt.core.PrivilegedConsentManagerImpl.listPurposes(PrivilegedConsentManagerImpl.java:222)
identity-server_1  |    at org.wso2.carbon.consent.mgt.endpoint.impl.ConsentsApiServiceImpl.getPurposeListResponseDTO(ConsentsApiServiceImpl.java:420)
.
.
.
identity-server_1  | Caused by: org.wso2.carbon.database.utils.jdbc.exceptions.DataAccessException: Error in performing Database query: '%s'SELECT ID, NAME, DESCRIPTION, PURPOSE_GROUP, GROUP_TYPE, TENANT_ID FROM CM_PURPOSE WHERE TENANT_ID = ? AND PURPOSE_GROUP LIKE ? AND GROUP_TYPE LIKE ? ORDER BY ID ASC LIMIT ? OFFSET ?
identity-server_1  |    at org.wso2.carbon.database.utils.jdbc.JdbcTemplate.executeQuery(JdbcTemplate.java:169)
identity-server_1  |    at org.wso2.carbon.consent.mgt.core.dao.impl.PurposeDAOImpl.listPurposes(PurposeDAOImpl.java:233)
identity-server_1  |    ... 61 more
identity-server_1  | Caused by: java.sql.SQLSyntaxErrorException: Table 'WSO2IS_IDENTITY_DB.CM_PURPOSE' doesn't exist
identity-server_1  |    at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
identity-server_1  |    at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
```
**Suggested Labels:**
wso2is:5.10.0

**Affected Product Version:**
docker image wso2/wso2is:5.10.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
1. git clone $url_repo:tag-5.10.0
1. docker-compose up -d
1. Activate the self-register in the admin-console
1. Go to portal page https://localhost:9443/user-portal and clic in Create Account
1. Write a new username and clic into *Proceed to Self Register*

**Related Issues:**
https://github.com/wso2/product-is/issues/3564

**Comment by omindu** [comment]
@oscarvesga Thanks for reporting this.

@ThilinaManamgoda Can we include the SQLs in [1] to the composer sql script [2] ?

[1] - https://github.com/wso2/carbon-consent-management/blob/v2.2.8/features/org.wso2.carbon.consent.mgt.server.feature/resources/dbscripts/mysql.sql
[2] - https://github.com/wso2/docker-is/blob/master/docker-compose/is/mysql/scripts/mysql_identity.sql

**Comment by chirangaalwis** [comment]
Fixed in https://github.com/wso2/docker-is/pull/199.

**Comment by oscarvesga** [comment]
Thank you, I confirm that now I can use the docker image `wso2/wso2is:5.10.0` with the self-registration
